[package]
name = "rust_painter_iced"
version = "0.2.0"
edition = "2024"

[dependencies]
# New architecture: iced + tiny_skia
iced = { version = "0.12", features = ["canvas", "tokio"] }
tiny-skia = "0.11"
uuid = { version = "1.0", features = ["v4"] }
